=== Cipher-Text/geo-vault/schemas/bd/admin2.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://geo-vault.local/schemas/bd/admin2.schema.json",
  "title": "Bangladesh District (Admin Level 2)",
  "type": "object",
  "required": [
    "id",
    "division_id",
    "name",
    "bn_name",
    "slug",
    "country_code",
    "admin_level",
    "pcode",
    "division_pcode",
    "lat",
    "lon",
    "center_lat",
    "center_lon",
    "area_sqkm",
    "url",
    "upazila_count",
    "union_count"
  ],
  "additionalProperties": false,
  "properties": {
    "id": { "type": "string" },
    "division_id": { "type": "string" },
    "name": { "type": "string" },
    "bn_name": { "type": "string" },
    "slug": { "type": "string" },
    "country_code": { "type": "string" },
    "admin_level": { "type": "string" },
    "pcode": { "type": "string" },
    "division_pcode": { "type": "string" },
    "lat": { "type": "string" },
    "lon": { "type": "string" },
    "center_lat": { "type": "string" },
    "center_lon": { "type": "string" },
    "area_sqkm": { "type": "string" },
    "url": { "type": "string" },
    "upazila_count": { "type": "string" },
    "union_count": { "type": "string" }
  }
}

=== Cipher-Text/geo-vault/data/bd/districts.json
[
  {
    "id": "1",
    "division_id": "1",
    "name": "Comilla",
    "bn_name": "কুমিল্লা",
    "slug": "comilla",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2019",
    "division_pcode": "BD20",
    "lat": "23.4682747",
    "lon": "91.1788135",
    "center_lat": "23.43704815",
    "center_lon": "91.03297863",
    "area_sqkm": "3097.33937792",
    "url": "www.comilla.gov.bd",
    "upazila_count": "17",
    "union_count": "192"
  },
  {
    "id": "2",
    "division_id": "1",
    "name": "Feni",
    "bn_name": "ফেনী",
    "slug": "feni",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2030",
    "division_pcode": "BD20",
    "lat": "23.023231",
    "lon": "91.3840844",
    "center_lat": "22.99495456",
    "center_lon": "91.41199797",
    "area_sqkm": "929.47783669",
    "url": "www.feni.gov.bd",
    "upazila_count": "6",
    "union_count": "43"
  },
  {
    "id": "3",
    "division_id": "1",
    "name": "Brahmanbaria",
    "bn_name": "ব্রাহ্মণবাড়িয়া",
    "slug": "brahmanbaria",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2012",
    "division_pcode": "BD20",
    "lat": "23.9570904",
    "lon": "91.1119286",
    "center_lat": "23.95334265",
    "center_lon": "91.08317152",
    "area_sqkm": "1928.26864757",
    "url": "www.brahmanbaria.gov.bd",
    "upazila_count": "9",
    "union_count": "100"
  },
  {
    "id": "4",
    "division_id": "1",
    "name": "Rangamati",
    "bn_name": "রাঙ্গামাটি",
    "slug": "rangamati",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2084",
    "division_pcode": "BD20",
    "lat": "22.65561018",
    "lon": "92.17541121",
    "center_lat": "22.82507051",
    "center_lon": "92.28109045",
    "area_sqkm": "5643.29864602",
    "url": "www.rangamati.gov.bd",
    "upazila_count": "10",
    "union_count": "49"
  },
  {
    "id": "5",
    "division_id": "1",
    "name": "Noakhali",
    "bn_name": "নোয়াখালী",
    "slug": "noakhali",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2075",
    "division_pcode": "BD20",
    "lat": "22.869563",
    "lon": "91.099398",
    "center_lat": "22.65806244",
    "center_lon": "91.12949863",
    "area_sqkm": "3236.99995684",
    "url": "www.noakhali.gov.bd",
    "upazila_count": "9",
    "union_count": "89"
  },
  {
    "id": "6",
    "division_id": "1",
    "name": "Chandpur",
    "bn_name": "চাঁদপুর",
    "slug": "chandpur",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2013",
    "division_pcode": "BD20",
    "lat": "23.2332585",
    "lon": "90.6712912",
    "center_lat": "23.2611099",
    "center_lon": "90.74888906",
    "area_sqkm": "1719.82858231",
    "url": "www.chandpur.gov.bd",
    "upazila_count": "8",
    "union_count": "88"
  },
  {
    "id": "7",
    "division_id": "1",
    "name": "Lakshmipur",
    "bn_name": "লক্ষ্মীপুর",
    "slug": "lakshmipur",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2051",
    "division_pcode": "BD20",
    "lat": "22.942477",
    "lon": "90.841184",
    "center_lat": "22.85093416",
    "center_lon": "90.85368875",
    "area_sqkm": "1503.10893536",
    "url": "www.lakshmipur.gov.bd",
    "upazila_count": "5",
    "union_count": "57"
  },
  {
    "id": "8",
    "division_id": "1",
    "name": "Chattogram",
    "bn_name": "চট্টগ্রাম",
    "slug": "chattogram",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2015",
    "division_pcode": "BD20",
    "lat": "22.335109",
    "lon": "91.834073",
    "center_lat": "22.44673258",
    "center_lon": "91.8192279",
    "area_sqkm": "4879.23669021",
    "url": "www.chittagong.gov.bd",
    "upazila_count": "15",
    "union_count": "196"
  },
  {
    "id": "9",
    "division_id": "1",
    "name": "Coxsbazar",
    "bn_name": "কক্সবাজার",
    "slug": "coxsbazar",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2022",
    "division_pcode": "BD20",
    "lat": "21.44315751",
    "lon": "91.97381741",
    "center_lat": "21.47601131",
    "center_lon": "92.06251685",
    "area_sqkm": "2326.7008648",
    "url": "www.coxsbazar.gov.bd",
    "upazila_count": "9",
    "union_count": "69"
  },
  {
    "id": "10",
    "division_id": "1",
    "name": "Khagrachhari",
    "bn_name": "খাগড়াছড়ি",
    "slug": "khagrachhari",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2046",
    "division_pcode": "BD20",
    "lat": "23.119285",
    "lon": "91.984663",
    "center_lat": "23.17194143",
    "center_lon": "91.95645652",
    "area_sqkm": "2977.80470582",
    "url": "www.khagrachhari.gov.bd",
    "upazila_count": "9",
    "union_count": "36"
  },
  {
    "id": "11",
    "division_id": "1",
    "name": "Bandarban",
    "bn_name": "বান্দরবান",
    "slug": "bandarban",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD2003",
    "division_pcode": "BD20",
    "lat": "22.1953275",
    "lon": "92.2183773",
    "center_lat": "21.80450621",
    "center_lon": "92.36513578",
    "area_sqkm": "4591.01309293",
    "url": "www.bandarban.gov.bd",
    "upazila_count": "7",
    "union_count": "31"
  },
  {
    "id": "12",
    "division_id": "2",
    "name": "Sirajganj",
    "bn_name": "সিরাজগঞ্জ",
    "slug": "sirajganj",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5088",
    "division_pcode": "BD50",
    "lat": "24.4533978",
    "lon": "89.7006815",
    "center_lat": "24.39152372",
    "center_lon": "89.60146461",
    "area_sqkm": "2511.87134166",
    "url": "www.sirajganj.gov.bd",
    "upazila_count": "9",
    "union_count": "82"
  },
  {
    "id": "13",
    "division_id": "2",
    "name": "Pabna",
    "bn_name": "পাবনা",
    "slug": "pabna",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5076",
    "division_pcode": "BD50",
    "lat": "23.998524",
    "lon": "89.233645",
    "center_lat": "24.05304736",
    "center_lon": "89.38618128",
    "area_sqkm": "2391.82687311",
    "url": "www.pabna.gov.bd",
    "upazila_count": "9",
    "union_count": "73"
  },
  {
    "id": "14",
    "division_id": "2",
    "name": "Bogura",
    "bn_name": "বগুড়া",
    "slug": "bogura",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5010",
    "division_pcode": "BD50",
    "lat": "24.8465228",
    "lon": "89.377755",
    "center_lat": "24.82433095",
    "center_lon": "89.38040124",
    "area_sqkm": "2930.12778131",
    "url": "www.bogra.gov.bd",
    "upazila_count": "12",
    "union_count": "108"
  },
  {
    "id": "15",
    "division_id": "2",
    "name": "Rajshahi",
    "bn_name": "রাজশাহী",
    "slug": "rajshahi",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5081",
    "division_pcode": "BD50",
    "lat": "24.37230298",
    "lon": "88.56307623",
    "center_lat": "24.46837737",
    "center_lon": "88.6506542",
    "area_sqkm": "2422.60833827",
    "url": "www.rajshahi.gov.bd",
    "upazila_count": "9",
    "union_count": "71"
  },
  {
    "id": "16",
    "division_id": "2",
    "name": "Natore",
    "bn_name": "নাটোর",
    "slug": "natore",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5069",
    "division_pcode": "BD50",
    "lat": "24.420556",
    "lon": "89.000282",
    "center_lat": "24.38056174",
    "center_lon": "89.08741492",
    "area_sqkm": "1904.98111437",
    "url": "www.natore.gov.bd",
    "upazila_count": "7",
    "union_count": "52"
  },
  {
    "id": "17",
    "division_id": "2",
    "name": "Joypurhat",
    "bn_name": "জয়পুরহাট",
    "slug": "joypurhat",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5038",
    "division_pcode": "BD50",
    "lat": "25.09636876",
    "lon": "89.04004280",
    "center_lat": "25.09298379",
    "center_lon": "89.08381655",
    "area_sqkm": "965.86615981",
    "url": "www.joypurhat.gov.bd",
    "upazila_count": "5",
    "union_count": "32"
  },
  {
    "id": "18",
    "division_id": "2",
    "name": "Chapainawabganj",
    "bn_name": "চাঁপাইনবাবগঞ্জ",
    "slug": "chapainawabganj",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5070",
    "division_pcode": "BD50",
    "lat": "24.5965034",
    "lon": "88.2775122",
    "center_lat": "24.7155962",
    "center_lon": "88.26399218",
    "area_sqkm": "1689.37734036",
    "url": "www.chapainawabganj.gov.bd",
    "upazila_count": "5",
    "union_count": "45"
  },
  {
    "id": "19",
    "division_id": "2",
    "name": "Naogaon",
    "bn_name": "নওগাঁ",
    "slug": "naogaon",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD5064",
    "division_pcode": "BD50",
    "lat": "24.83256191",
    "lon": "88.92485205",
    "center_lat": "24.90021071",
    "center_lon": "88.7516789",
    "area_sqkm": "3438.80294377",
    "url": "www.naogaon.gov.bd",
    "upazila_count": "11",
    "union_count": "99"
  },
  {
    "id": "20",
    "division_id": "3",
    "name": "Jashore",
    "bn_name": "যশোর",
    "slug": "jashore",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD4041",
    "division_pcode": "BD40",
    "lat": "23.16643",
    "lon": "89.2081126",
    "center_lat": "23.08947488",
    "center_lon": "89.17481232",
    "area_sqkm": "2576.4179111",
    "url": "www.jessore.gov.bd",
    "upazila_count": "8",
    "union_count": "91"
  },
  {
    "id": "21",
    "division_id": "3",
    "name": "Satkhira",
    "bn_name": "সাতক্ষীরা",
    "slug": "satkhira",
    "country_code": "BD",
    "admin_level": "district",
    "pcode": "BD4087",
    "division_pcode": "BD40",
    "lat": "22.7180905",
    "lon": "89.0687033",
    "center_lat": "22.30789672",
    "center_lon": "89.14334959",
    "area_sqkm": "3962.99979627",
    "url": "www.satkhira.gov.bd",
    "upazila_count": "7",
    "union_count": "78"
  },
  {
    "id": "22",
    "division_id": "3",
    "name": "Meherpur",
    "bn_name": "মেহেরপুর",
    "slug": "meherpur",
    "country_code": "BD",
