=== Cipher-Text/geo-vault/schemas/admin1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://geo-vault.local/schemas/admin1.schema.json",
  "title": "Admin Level 1 Region",
  "description": "First-level administrative division (state, province, division, department, etc.)",
  "type": "object",
  "required": [
    "id",
    "name",
    "name_en",
    "local_name",
    "slug",
    "country_code",
    "country_iso3",
    "country_name",
    "admin_level",
    "type",
    "iso_3166_2",
    "adm1_code",
    "postal_code",
    "fips_code",
    "geoname_id",
    "geonames_admin1_code",
    "lat",
    "lon",
    "wikidata_id"
  ],
  "additionalProperties": false,
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" },
    "name_en": { "type": "string" },
    "local_name": { "type": "string" },
    "slug": { "type": "string" },
    "country_code": { "type": "string" },
    "country_iso3": { "type": "string" },
    "country_name": { "type": "string" },
    "admin_level": { "type": "string" },
    "type": { "type": "string" },
    "iso_3166_2": { "type": "string" },
    "adm1_code": { "type": "string" },
    "postal_code": { "type": "string" },
    "fips_code": { "type": "string" },
    "geoname_id": { "type": "string" },
    "geonames_admin1_code": { "type": "string" },
    "lat": { "type": "string" },
    "lon": { "type": "string" },
    "wikidata_id": { "type": "string" }
  }
}

=== Cipher-Text/geo-vault/data/countries/np/admin1.json
[
  {
    "id": "geonames-12095449",
    "name": "Bagmati Province",
    "name_en": "Bagmati Province",
    "local_name": "Bagmati Province",
    "slug": "bagmati-province",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "3",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095449",
    "geonames_admin1_code": "NP.3",
    "lat": "27.65249",
    "lon": "85.39536",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095450",
    "name": "Gandaki Pradesh",
    "name_en": "Gandaki Pradesh",
    "local_name": "Gandaki Pradesh",
    "slug": "gandaki-pradesh",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "4",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095450",
    "geonames_admin1_code": "NP.4",
    "lat": "28.38431",
    "lon": "84.03806",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095452",
    "name": "Karnali Province",
    "name_en": "Karnali Province",
    "local_name": "Karnali Province",
    "slug": "karnali-province",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "6",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095452",
    "geonames_admin1_code": "NP.6",
    "lat": "29.29913",
    "lon": "82.4769",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095447",
    "name": "Koshi",
    "name_en": "Koshi",
    "local_name": "Koshi",
    "slug": "koshi",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "1",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095447",
    "geonames_admin1_code": "NP.1",
    "lat": "27.23006",
    "lon": "87.18018",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095451",
    "name": "Lumbini Province",
    "name_en": "Lumbini Province",
    "local_name": "Lumbini Province",
    "slug": "lumbini-province",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "5",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095451",
    "geonames_admin1_code": "NP.5",
    "lat": "28.09952",
    "lon": "82.524",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095448",
    "name": "Madhesh",
    "name_en": "Madhesh",
    "local_name": "Madhesh",
    "slug": "madhesh",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "2",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095448",
    "geonames_admin1_code": "NP.2",
    "lat": "26.94242",
    "lon": "85.61",
    "wikidata_id": ""
  },
  {
    "id": "geonames-12095453",
    "name": "Sudurpashchim Pradesh",
    "name_en": "Sudurpashchim Pradesh",
    "local_name": "Sudurpashchim Pradesh",
    "slug": "sudurpashchim-pradesh",
    "country_code": "NP",
    "country_iso3": "NPL",
    "country_name": "Nepal",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "",
    "adm1_code": "7",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "12095453",
    "geonames_admin1_code": "NP.7",
    "lat": "29.32055",
    "lon": "80.92063",
    "wikidata_id": ""
  }
]

=== Cipher-Text/geo-vault/data/countries/pk/admin1.json
[
  {
    "id": "ne-pak-1109",
    "name": "Azad Kashmir",
    "name_en": "Azad Kashmir",
    "local_name": "",
    "slug": "azad-kashmir",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Centrally Administered Area",
    "iso_3166_2": "PK-JK",
    "adm1_code": "PAK-1109",
    "postal_code": "JK",
    "fips_code": "PK06",
    "geoname_id": "1184196",
    "geonames_admin1_code": "PK.06",
    "lat": "33.868",
    "lon": "73.8036",
    "wikidata_id": "Q200130"
  },
  {
    "id": "ne-pak-1108",
    "name": "Baluchistan",
    "name_en": "Balochistan",
    "local_name": "",
    "slug": "baluchistan",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "PK-BA",
    "adm1_code": "PAK-1108",
    "postal_code": "BA",
    "fips_code": "PK02",
    "geoname_id": "1183606",
    "geonames_admin1_code": "PK.02",
    "lat": "27.5194",
    "lon": "65.5512",
    "wikidata_id": "Q163239"
  },
  {
    "id": "ne-pak-1112",
    "name": "F.A.T.A.",
    "name_en": "Federally Administered Tribal Areas",
    "local_name": "",
    "slug": "f-a-t-a",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Territory",
    "iso_3166_2": "PK-TA",
    "adm1_code": "PAK-1112",
    "postal_code": "TA",
    "fips_code": "PK01",
    "geoname_id": "1179245",
    "geonames_admin1_code": "PK.01",
    "lat": "32.6148",
    "lon": "69.8985",
    "wikidata_id": "Q208270"
  },
  {
    "id": "ne-pak-1110",
    "name": "F.C.T.",
    "name_en": "Islamabad Capital Territory",
    "local_name": "",
    "slug": "f-c-t",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Capital Territory",
    "iso_3166_2": "PK-IS",
    "adm1_code": "PAK-1110",
    "postal_code": "IS",
    "fips_code": "PK08",
    "geoname_id": "1162015",
    "geonames_admin1_code": "PK.08",
    "lat": "33.7011",
    "lon": "73.0628",
    "wikidata_id": "Q848613"
  },
  {
    "id": "ne-pak-1123",
    "name": "K.P.",
    "name_en": "Khyber Pakhtunkhwa",
    "local_name": "",
    "slug": "k-p",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "PK-KP",
    "adm1_code": "PAK-1123",
    "postal_code": "NW",
    "fips_code": "PK03",
    "geoname_id": "1168873",
    "geonames_admin1_code": "PK.03",
    "lat": "34.9407",
    "lon": "72.6402",
    "wikidata_id": "Q183314"
  },
  {
    "id": "ne-pak-1111",
    "name": "Northern Areas",
    "name_en": "Gilgit-Baltistan",
    "local_name": "",
    "slug": "northern-areas",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Centrally Administered Area",
    "iso_3166_2": "PK-GB",
    "adm1_code": "PAK-1111",
    "postal_code": "NA",
    "fips_code": "PK07",
    "geoname_id": "1168878",
    "geonames_admin1_code": "PK.07",
    "lat": "35.7864",
    "lon": "74.9848",
    "wikidata_id": "Q200697"
  },
  {
    "id": "ne-pak-1113",
    "name": "Punjab",
    "name_en": "Punjab",
    "local_name": "",
    "slug": "punjab",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "PK-PB",
    "adm1_code": "PAK-1113",
    "postal_code": "PB",
    "fips_code": "PK04",
    "geoname_id": "1167710",
    "geonames_admin1_code": "PK.04",
    "lat": "31.3589",
    "lon": "72.3449",
    "wikidata_id": "Q4478"
  },
  {
    "id": "ne-pak-1114",
    "name": "Sind",
    "name_en": "Sindh",
    "local_name": "",
    "slug": "sind",
    "country_code": "PK",
    "country_iso3": "PAK",
    "country_name": "Pakistan",
    "admin_level": "admin1",
    "type": "Province",
    "iso_3166_2": "PK-SD",
    "adm1_code": "PAK-1114",
    "postal_code": "SD",
    "fips_code": "PK05",
    "geoname_id": "1164807",
    "geonames_admin1_code": "PK.05",
    "lat": "26.3734",
    "lon": "68.8685",
    "wikidata_id": "Q37211"
  }
]

=== Cipher-Text/geo-vault/data/mm/admin1.json
[
  {
    "id": "geonames-1321850",
    "name": "Ayeyarwady Region",
    "name_en": "Ayeyarwady Region",
    "local_name": "Ayeyarwady Region",
    "slug": "ayeyarwady-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "03",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1321850",
    "geonames_admin1_code": "MM.03",
    "lat": "17",
    "lon": "95",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1300463",
    "name": "Bago Region",
    "name_en": "Bago Region",
    "local_name": "Bago Region",
    "slug": "bago-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "16",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1300463",
    "geonames_admin1_code": "MM.16",
    "lat": "18.25",
    "lon": "96.25",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1327132",
    "name": "Chin State",
    "name_en": "Chin State",
    "local_name": "Chin State",
    "slug": "chin-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "02",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1327132",
    "geonames_admin1_code": "MM.02",
    "lat": "22",
    "lon": "93.5",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1321702",
    "name": "Kachin State",
    "name_en": "Kachin State",
    "local_name": "Kachin State",
    "slug": "kachin-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "04",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1321702",
    "geonames_admin1_code": "MM.04",
    "lat": "26",
    "lon": "97.5",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1319539",
    "name": "Kayah State",
    "name_en": "Kayah State",
    "local_name": "Kayah State",
    "slug": "kayah-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "06",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1319539",
    "geonames_admin1_code": "MM.06",
    "lat": "19.25",
    "lon": "97.5",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1320233",
    "name": "Kayin State",
    "name_en": "Kayin State",
    "local_name": "Kayin State",
    "slug": "kayin-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "05",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1320233",
    "geonames_admin1_code": "MM.05",
    "lat": "17.5",
    "lon": "97.75",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1312604",
    "name": "Magway Region",
    "name_en": "Magway Region",
    "local_name": "Magway Region",
    "slug": "magway-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "15",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1312604",
    "geonames_admin1_code": "MM.15",
    "lat": "20.5",
    "lon": "94.75",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1311871",
    "name": "Mandalay Region",
    "name_en": "Mandalay Region",
    "local_name": "Mandalay Region",
    "slug": "mandalay-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "08",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1311871",
    "geonames_admin1_code": "MM.08",
    "lat": "21",
    "lon": "96",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1308528",
    "name": "Mon State",
    "name_en": "Mon State",
    "local_name": "Mon State",
    "slug": "mon-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "13",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1308528",
    "geonames_admin1_code": "MM.13",
    "lat": "16.25",
    "lon": "97.75",
    "wikidata_id": ""
  },
  {
    "id": "geonames-8239588",
    "name": "Nay Pyi Taw",
    "name_en": "Nay Pyi Taw",
    "local_name": "Nay Pyi Taw",
    "slug": "nay-pyi-taw",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "18",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "8239588",
    "geonames_admin1_code": "MM.18",
    "lat": "19.8822",
    "lon": "96.14182",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1298852",
    "name": "Rakhine State",
    "name_en": "Rakhine State",
    "local_name": "Rakhine State",
    "slug": "rakhine-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "01",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1298852",
    "geonames_admin1_code": "MM.01",
    "lat": "19",
    "lon": "94.25",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1298480",
    "name": "Sagaing Region",
    "name_en": "Sagaing Region",
    "local_name": "Sagaing Region",
    "slug": "sagaing-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "10",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1298480",
    "geonames_admin1_code": "MM.10",
    "lat": "23.5",
    "lon": "95.5",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1297099",
    "name": "Shan State",
    "name_en": "Shan State",
    "local_name": "Shan State",
    "slug": "shan-state",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "11",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1297099",
    "geonames_admin1_code": "MM.11",
    "lat": "22",
    "lon": "98",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1293118",
    "name": "Tanintharyi Region",
    "name_en": "Tanintharyi Region",
    "local_name": "Tanintharyi Region",
    "slug": "tanintharyi-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "12",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1293118",
    "geonames_admin1_code": "MM.12",
    "lat": "13",
    "lon": "99",
    "wikidata_id": ""
  },
  {
    "id": "geonames-1298822",
    "name": "Yangon Region",
    "name_en": "Yangon Region",
    "local_name": "Yangon Region",
    "slug": "yangon-region",
    "country_code": "MM",
    "country_iso3": "MMR",
    "country_name": "Myanmar",
    "admin_level": "admin1",
    "type": "State/Region",
    "iso_3166_2": "",
    "adm1_code": "17",
    "postal_code": "",
    "fips_code": "",
    "geoname_id": "1298822",
    "geonames_admin1_code": "MM.17",
    "lat": "17",
    "lon": "96.16667",
    "wikidata_id": ""
  }
]
