=== Cipher-Text/geo-vault/schemas/bd-division.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://geo-vault.local/schemas/bd-division.schema.json",
  "title": "Bangladesh Division",
  "type": "object",
  "required": [
    "id",
    "name",
    "bn_name",
    "slug",
    "country_code",
    "admin_level",
    "pcode",
    "area_sqkm",
    "center_lat",
    "center_lon",
    "url",
    "district_count",
    "upazila_count",
    "union_count"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "bn_name": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "country_code": {
      "type": "string"
    },
    "admin_level": {
      "type": "string"
    },
    "pcode": {
      "type": "string"
    },
    "area_sqkm": {
      "type": "string"
    },
    "center_lat": {
      "type": "string"
    },
    "center_lon": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "district_count": {
      "type": "string"
    },
    "upazila_count": {
      "type": "string"
    },
    "union_count": {
      "type": "string"
    }
  }
}

=== Cipher-Text/geo-vault/data/bd/divisions.json
[
  {
    "id": "1",
    "name": "Chattagram",
    "bn_name": "চট্টগ্রাম",
    "slug": "chattagram",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD20",
    "area_sqkm": "32833.07733648",
    "center_lat": "22.70130794",
    "center_lon": "91.70586117",
    "url": "www.chittagongdiv.gov.bd",
    "district_count": "11",
    "upazila_count": "104",
    "union_count": "950"
  },
  {
    "id": "2",
    "name": "Rajshahi",
    "bn_name": "রাজশাহী",
    "slug": "rajshahi",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD50",
    "area_sqkm": "18255.46189267",
    "center_lat": "24.58933841",
    "center_lon": "89.04636294",
    "url": "www.rajshahidiv.gov.bd",
    "district_count": "8",
    "upazila_count": "67",
    "union_count": "562"
  },
  {
    "id": "3",
    "name": "Khulna",
    "bn_name": "খুলনা",
    "slug": "khulna",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD40",
    "area_sqkm": "22584.72427649",
    "center_lat": "22.83771757",
    "center_lon": "89.3047787",
    "url": "www.khulnadiv.gov.bd",
    "district_count": "10",
    "upazila_count": "59",
    "union_count": "574"
  },
  {
    "id": "4",
    "name": "Barisal",
    "bn_name": "বরিশাল",
    "slug": "barisal",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD10",
    "area_sqkm": "12693.47055445",
    "center_lat": "22.39284273",
    "center_lon": "90.40639487",
    "url": "www.barisaldiv.gov.bd",
    "district_count": "6",
    "upazila_count": "42",
    "union_count": "349"
  },
  {
    "id": "5",
    "name": "Sylhet",
    "bn_name": "সিলেট",
    "slug": "sylhet",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD60",
    "area_sqkm": "12373.31177366",
    "center_lat": "24.71528851",
    "center_lon": "91.66471318",
    "url": "www.sylhetdiv.gov.bd",
    "district_count": "4",
    "upazila_count": "40",
    "union_count": "336"
  },
  {
    "id": "6",
    "name": "Dhaka",
    "bn_name": "ঢাকা",
    "slug": "dhaka",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD30",
    "area_sqkm": "20426.53173259",
    "center_lat": "23.83902131",
    "center_lon": "90.24215888",
    "url": "www.dhakadiv.gov.bd",
    "district_count": "13",
    "upazila_count": "89",
    "union_count": "876"
  },
  {
    "id": "7",
    "name": "Rangpur",
    "bn_name": "রংপুর",
    "slug": "rangpur",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD55",
    "area_sqkm": "16282.75269198",
    "center_lat": "25.78042102",
    "center_lon": "89.05409536",
    "url": "www.rangpurdiv.gov.bd",
    "district_count": "8",
    "upazila_count": "58",
    "union_count": "541"
  },
  {
    "id": "8",
    "name": "Mymensingh",
    "bn_name": "ময়মনসিংহ",
    "slug": "mymensingh",
    "country_code": "BD",
    "admin_level": "division",
    "pcode": "BD45",
    "area_sqkm": "10512.77412986",
    "center_lat": "24.84783035",
    "center_lon": "90.38174541",
    "url": "www.mymensinghdiv.gov.bd",
    "district_count": "4",
    "upazila_count": "35",
    "union_count": "352"
  }
]
